import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApiProvider } from "@/utils/ApiProvider";
import Navbar from "@/components/Header/Navbar";
import SearchBar from "@/components/Header/SearchBar";
import BackToTopButton from "@/components/Utility/BackToTopButton";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Art Exhibitor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApiProvider>
      <html lang="en">
        <body className={inter.className}>
          <section className='py-24'>
            <Navbar />
            <h1 className="text-5xl font-bold mx-auto text-center mt-28 md-16 hidden sm:block">Explore the World of Art</h1>


            <SearchBar />
          </section>
          {children}
          <BackToTopButton /> 
        </body>
      </html>
    </ApiProvider>
  );
}
